### ISSUE TITLE
可否加入這次裝甲超夢的IV表?

### ISSUE THREAD

**Issue by Speedman29** [Rplus/Pokemon-CP-list#14]
請加入這次裝甲超夢的IV表，以方便查詢，感謝

**Comment by Rplus** [comment]
![image](https://user-images.githubusercontent.com/1808835/61343795-a7bdeb80-a881-11e9-9b66-73831c66fbad.png)
重新整理應該就有囉

https://github.com/Rplus/Pokemon-CP-list/commit/2e6434c0402e1e6db7b16fd5628908e376f7209a

**Comment by Speedman29** [comment]
感謝
